"""Flag locations for the check_flags command."""

location_flag_to_name = {
    1: "Japes Lanky Grape Gate Barrel",
    2: "Japes Tiny Feather Gate Barrel",
    3: "Japes Donkey Baboon Blast",
    4: "Japes in Front of Diddy Cage",
    5: "Japes Free Diddy Item",
    6: "Kong Unlocked: Diddy",
    8: "Japes Tiny Stump",
    9: "Japes Tiny Beehive",
    10: "Japes Lanky Painting Room Zingers",
    11: "Japes Lanky Slope Barrel",
    12: "Japes Chunky Underground",
    18: "Japes Diddy Timed Cage Banana",
    19: "Japes Lanky Timed Cage Banana",
    20: "Japes Donkey Floor Cage Banana",
    21: "Japes Tiny Timed Cage Banana",
    22: "Japes Chunky Timed Cage Banana",
    23: "Japes Diddy Top of Mountain",
    24: "Japes Diddy Minecart",
    25: "Japes Chunky Boulder",
    26: "Japes Boss Defeated",
    28: "Japes Chunky Giant Bonus Barrel",
    31: "Japes Diddy Peanut Tunnel",
    49: "Aztec Chunky Vases",
    51: "Aztec Donkey Free Llama Blast",
    52: "Aztec Chunky Giant Caged Barrel",
    54: "Aztec Diddy Ram Gongs",
    56: "Aztec Diddy 5 Door Temple",
    57: "Aztec Donkey 5 Door Temple",
    58: "Aztec Tiny 5 Door Temple",
    59: "Aztec Chunky 5 Door Temple",
    60: "Aztec Lanky 5 Door Temple",
    62: "Aztec Donkey Sealed Quicksand Tunnel Barrel",
    63: "Aztec Diddy Vulture Race",
    64: "Aztec Chunky Klaptrap Room",
    65: "Aztec Tiny Klaptrap Room",
    66: "Kong Unlocked: Tiny",
    67: "Aztec Free Tiny Item",
    68: "Aztec Lanky Vulture Shooting",
    70: "Kong Unlocked: Lanky",
    71: "Aztec Tiny Llama Temple Lava Pedestals",
    72: "Aztec Lanky Matching Game",
    73: "Aztec Lanky Llama Temple Barrel",
    74: "Aztec Boss Defeated",
    75: "Aztec Tiny Beetle Race",
    77: "Aztec Free Lanky Item",
    112: "Factory Donkey Power Hut",
    113: "Factory Diddy Production Spring",
    114: "Factory Chunky Production Timer",
    115: "Factory Lanky Production Handstand",
    116: "Factory Tiny Production Twirl",
    117: "Kong Unlocked: Chunky",
    118: "Factory Free Chunky Item",
    121: "Factory Chunky Dark Room",
    122: "Factory Donkey Number Game",
    123: "Factory Tiny Mini by Arcade",
    124: "Factory Tiny Dartboard",
    125: "Factory Lanky Piano Game",
    126: "Factory Diddy Charge Enemies",
    127: "Factory Chunky Toy Monster",
    128: "Factory Donkey Crusher Room",
    130: "Factory Donkey DK Arcade Round 1",
    132: "DK Arcade Round 2",
    134: "Factory Diddy Storage Room Barrel",
    135: "Factory Diddy Block Tower",
    136: "Factory Chunky Barrel by Arcade",
    137: "Factory Lanky Testing Room Barrel",
    138: "Factory Boss Defeated",
    139: "Factory Tiny Car Race",
    154: "Galleon Chunky Cannon Game",
    157: "Galleon Donkey Lighthouse",
    163: "Galleon Diddy Gold Tower Barrel",
    164: "Galleon Lanky Gold Tower Barrel",
    165: "Galleon Donkey Seal Race",
    166: "Galleon Chunky Seasick",
    167: "Galleon Diddy Mechfish",
    168: "Galleon Boss Defeated",
    182: "Galleon Chunky Chest",
    183: "Galleon Lanky 2 Door Ship",
    184: "Galleon Tiny 2 Door Ship",
    191: "Galleon Tiny Mermaid Reward",
    192: "Galleon Lanky Enguarde Chest",
    193: "Galleon Donkey Free the Seal",
    197: "Galleon Chunky 5 Door Ship",
    198: "Galleon Diddy 5 Door Ship",
    199: "Galleon Lanky 5 Door Ship",
    200: "Galleon Donkey 5 Door Ship",
    201: "Galleon Tiny 5 Door Ship",
    202: "Galleon Tiny Submarine Barrel",
    204: "Galleon Diddy Top of Lighthouse",
    205: "Forest Tiny Anthill Banana",
    209: "Forest Tiny Top of the Beanstalk",
    211: "Forest Diddy Top of Mushroom Barrel",
    214: "Forest Diddy Winch Cage",
    215: "Forest Chunky Minecart",
    216: "Forest Diddy Dark Rafters",
    217: "Forest Lanky Attic Shooting",
    219: "Forest Donkey Mill Levers",
    221: "Forest Chunky Keg Crushing",
    224: "Forest Lanky Colored Mushroom Slam",
    225: "Forest Chunky Face Puzzle",
    226: "Forest Lanky Zinger Bounce",
    227: "Forest Tiny Mushroom Barrel",
    228: "Forest Donkey Mushroom Cannons",
    235: "Forest Donkey Thornvine Barn Barrel",
    236: "Forest Boss Defeated",
    247: "Forest Tiny Spider Boss",
    249: "Forest Lanky Rabbit Race",
    250: "Forest Diddy Owl Race",
    253: "Forest Chunky Apple Rescue",
    254: "Forest Donkey Baboon Blast",
    259: "Caves Lanky Beetle Race",
    260: "Caves Tiny 5 Door Cabin",
    261: "Caves Donkey 5 Door Cabin",
    262: "Caves Diddy 5 Door Cabin Lower",
    263: "Caves Chunky 5 Door Cabin",
    264: "Caves Lanky Sprint Cabin",
    268: "Caves Chunky Gorilla Gone",
    270: "Caves Chunky Transparent Igloo",
    271: "Caves Lanky Ice Castle Slam Challenge",
    274: "Caves Diddy 5 Door Igloo",
    275: "Caves Donkey 5 Door Igloo",
    276: "Caves Donkey Rotating Cabin",
    278: "Caves Chunky 5 Door Igloo",
    279: "Caves Tiny 5 Door Igloo",
    281: "Caves Lanky 5 Door Igloo",
    292: "Caves Boss Defeated",
    293: "Caves Diddy 5 Door Cabin Upper",
    294: "Caves Diddy Jetpack Barrel",
    295: "Caves Tiny Mini Cave Barrel",
    297: "Caves Tiny Monkeyport Igloo",
    298: "Caves Donkey Baboon Blast",
    301: "Returning the Banana Fairies",
    305: "Castle Diddy Ballroom",
    306: "Castle Lanky Tower",
    308: "Castle Lanky Mausoleum",
    309: "Castle Tiny Mausoleum",
    310: "Castle Diddy Crypt",
    311: "Castle Chunky Crypt",
    313: "Castle Donkey Library",
    314: "Castle Chunky Museum",
    315: "Castle Tiny Over Chasm",
    316: "Castle Lanky Dungeon",
    317: "Castle Boss Defeated",
    318: "Castle Donkey Minecart",
    319: "Castle Chunky Tree Sniping Barrel",
    320: "Castle Donkey Tree Sniping",
    322: "Castle Chunky Shed",
    323: "Castle Lanky Greenhouse",
    325: "Castle Tiny Car Race",
    326: "Castle Donkey Dungeon",
    350: "Castle Diddy Above Castle",
    351: "Castle Tiny Trash Can",
    353: "Castle Diddy Dungeon",
    379: "Jetpac",
    380: "The End of Helm",
    381: "Isles Japes Lobby Entrance Item",
    385: "Kong Unlocked: Donkey",
    398: "Isles Lanky Japes Instrument",
    402: "Isles Tiny Aztec Lobby Barrel",
    403: "Isles Tiny Galleon Lobby Swim",
    404: "Isles Donkey Bongos Pad",
    406: "Isles Chunky Helm Lobby Barrel",
    410: "Isles Diddy Guitar Pad",
    411: "Isles Donkey Caves Lava",
    415: "Isles Lanky Castle Lobby Barrel",
    416: "Isles Diddy Snides Spring Barrel",
    419: "Isles Donkey Coconut Cage",
    420: "Isles Tiny Feather Cage",
    421: "Isles Lanky Grape Cage",
    422: "Isles Chunky Pineapple Cage",
    423: "Isles Diddy Peanut Cage",
    424: "Isles Chunky Triangle Pad",
    425: "Isles Tiny Saxophone Pad",
    428: "Isles Diddy Summit Barrel",
    429: "Isles Lanky Sprint Cage",
    431: "Isles Chunky Pound the X",
    444: "Key 1 Turned",
    445: "Key 2 Turned",
    446: "Key 3 Turned",
    447: "Key 4 Turned",
    448: "Key 5 Turned",
    449: "Key 6 Turned",
    450: "Key 7 Turned",
    451: "Key 8 Turned",
    469: "Japes Kasplat: Hive Tunnel Lower",
    470: "Japes Kasplat: Near Painting Room",
    471: "Japes Kasplat: By Lanky Slope Bonus",
    472: "Japes Kasplat: Hive Tunnel Upper",
    473: "Japes Kasplat: Underground",
    474: "Aztec Kasplat: Behind DK Stone Door",
    475: "Aztec Kasplat: On Tiny Temple",
    476: "Aztec Kasplat: Llama Temple Lava",
    477: "Aztec Kasplat: Hunky Chunky Barrel",
    478: "Aztec Kasplat: Chunky 5-Door Temple",
    479: "Factory Kasplat: Upper Production Pipe",
    480: "Factory Kasplat: Base of Production",
    481: "Factory Kasplat: Research and Development",
    482: "Factory Kasplat: Pole to Arcade",
    483: "Factory Kasplat: Block Tower",
    484: "Galleon Kasplat: Diddy Gold Tower",
    485: "Galleon Kasplat: Lighthouse Alcove",
    486: "Galleon Kasplat: Cannon Game Room",
    487: "Galleon Kasplat: Past Vines",
    488: "Galleon Kasplat: Musical Cactus",
    489: "Forest Kasplat: Behind DK's Barn",
    490: "Forest Kasplat: Inside Giant Mushroom",
    491: "Forest Kasplat: Under Owl Tree",
    492: "Forest Kasplat: Low Mushroom Exterior",
    493: "Forest Kasplat: Mushroom Night Door",
    494: "Caves Kasplat: Near Ice Castle",
    495: "Caves Kasplat: Mini Room by Funky",
    496: "Caves Kasplat: On the Pillar",
    497: "Caves Kasplat: By the Far Warp 2",
    498: "Caves Kasplat: On 5-Door Igloo",
    499: "Castle Kasplat: Inside the Tree",
    500: "Castle Kasplat: Lower Cave Center",
    501: "Castle Kasplat: Near Upper Warp 2",
    502: "Castle Kasplat: On a lone platform",
    503: "Castle Kasplat: Near Candy's",
    504: "Isles Kasplat: Helm Lobby",
    505: "Isles Kasplat: Castle Lobby",
    506: "Isles Kasplat: Caves Lobby Punch",
    507: "Isles Kasplat: Factory Lobby Box",
    508: "Isles Kasplat: Galleon Lobby",
    509: "Turn In Jungle Japes Donkey Blueprint",
    510: "Turn In Jungle Japes Diddy Blueprint",
    511: "Turn In Jungle Japes Lanky Blueprint",
    512: "Turn In Jungle Japes Tiny Blueprint",
    513: "Turn In Jungle Japes Chunky Blueprint",
    514: "Turn In Angry Aztec Donkey Blueprint",
    515: "Turn In Angry Aztec Diddy Blueprint",
    516: "Turn In Angry Aztec Lanky Blueprint",
    517: "Turn In Angry Aztec Tiny Blueprint",
    518: "Turn In Angry Aztec Chunky Blueprint",
    519: "Turn In Frantic Factory Donkey Blueprint",
    520: "Turn In Frantic Factory Diddy Blueprint",
    521: "Turn In Frantic Factory Lanky Blueprint",
    522: "Turn In Frantic Factory Tiny Blueprint",
    523: "Turn In Frantic Factory Chunky Blueprint",
    524: "Turn In Gloomy Galleon Donkey Blueprint",
    525: "Turn In Gloomy Galleon Diddy Blueprint",
    526: "Turn In Gloomy Galleon Lanky Blueprint",
    527: "Turn In Gloomy Galleon Tiny Blueprint",
    528: "Turn In Gloomy Galleon Chunky Blueprint",
    529: "Turn In Forest Forest Donkey Blueprint",
    530: "Turn In Forest Forest Diddy Blueprint",
    531: "Turn In Forest Forest Lanky Blueprint",
    532: "Turn In Forest Forest Tiny Blueprint",
    533: "Turn In Forest Forest Chunky Blueprint",
    534: "Turn In Crystal Caves Donkey Blueprint",
    535: "Turn In Crystal Caves Diddy Blueprint",
    536: "Turn In Crystal Caves Lanky Blueprint",
    537: "Turn In Crystal Caves Tiny Blueprint",
    538: "Turn In Crystal Caves Chunky Blueprint",
    539: "Turn In Creepy Castle Donkey Blueprint",
    540: "Turn In Creepy Castle Diddy Blueprint",
    541: "Turn In Creepy Castle Lanky Blueprint",
    542: "Turn In Creepy Castle Tiny Blueprint",
    543: "Turn In Creepy Castle Chunky Blueprint",
    544: "Turn In Donkey Isles Donkey Blueprint",
    545: "Turn In Donkey Isles Diddy Blueprint",
    546: "Turn In Donkey Isles Lanky Blueprint",
    547: "Turn In Donkey Isles Tiny Blueprint",
    548: "Turn In Donkey Isles Chunky Blueprint",
    549: "Japes Donkey Medal",
    550: "Japes Diddy Medal",
    551: "Japes Lanky Medal",
    552: "Japes Tiny Medal",
    553: "Japes Chunky Medal",
    554: "Aztec Donkey Medal",
    555: "Aztec Diddy Medal",
    556: "Aztec Lanky Medal",
    557: "Aztec Tiny Medal",
    558: "Aztec Chunky Medal",
    559: "Factory Donkey Medal",
    560: "Factory Diddy Medal",
    561: "Factory Lanky Medal",
    562: "Factory Tiny Medal",
    563: "Factory Chunky Medal",
    564: "Galleon Donkey Medal",
    565: "Galleon Diddy Medal",
    566: "Galleon Lanky Medal",
    567: "Galleon Tiny Medal",
    568: "Galleon Chunky Medal",
    569: "Forest Donkey Medal",
    570: "Forest Diddy Medal",
    571: "Forest Lanky Medal",
    572: "Forest Tiny Medal",
    573: "Forest Chunky Medal",
    574: "Caves Donkey Medal",
    575: "Caves Diddy Medal",
    576: "Caves Lanky Medal",
    577: "Caves Tiny Medal",
    578: "Caves Chunky Medal",
    579: "Castle Donkey Medal",
    580: "Castle Diddy Medal",
    581: "Castle Lanky Medal",
    582: "Castle Tiny Medal",
    583: "Castle Chunky Medal",
    584: "Helm Donkey Medal",
    585: "Helm Diddy Medal",
    586: "Helm Lanky Medal",
    587: "Helm Tiny Medal",
    588: "Helm Chunky Medal",
    589: "Japes Fairy (Rambi Door Pool)",
    590: "Japes Fairy (Painting Room)",
    591: "Factory Fairy (Near Funky's)",
    592: "Galleon Fairy (In Punch Chest)",
    593: "Isles Fairy (Factory Lobby)",
    594: "Isles Fairy (Forest Lobby)",
    595: "Forest Fairy (Dark Rafters)",
    596: "Forest Fairy (Thornvine Barn)",
    597: "Caves Fairy (Tiny Igloo)",
    598: "Helm Fairy (Key 8 Room (1))",
    599: "Helm Fairy (Key 8 Room (2))",
    600: "Aztec Fairy (Llama Temple)",
    601: "Aztec Fairy (Tiny 5-Door Temple)",
    602: "Factory Fairy (Number Game)",
    603: "Galleon Fairy (In Tiny's 5-Door Ship)",
    604: "Castle Fairy (Near Car Race)",
    605: "Castle Fairy (Tree Sniper Room)",
    606: "Isles Fairy (Small Island)",
    607: "Isles Fairy (Upper Krem Isles)",
    608: "Caves Fairy (Diddy Candles Cabin)",
    609: "Japes Battle Arena (Near Funky)",
    610: "Aztec Battle Arena (Tiny Temple: Vulture Room)",
    611: "Factory Battle Arena (Under R and D Grate)",
    612: "Galleon Battle Arena (Under Cranky)",
    613: "Forest Battle Arena (Giant Mushroom High Ladder Platform)",
    614: "Isles Battle Arena 2 (Fungi Lobby: Gorilla Gone Box)",
    615: "Isles Battle Arena 1 (Snide's Room: Under Rock)",
    616: "Caves Battle Arena (Rotating Room: Left Portion)",
    617: "Castle Battle Arena (Greenhouse: Center)",
    618: "Helm Battle Arena (Top of Blast-o-Matic)",
    670: "Japes Dirt: Painting Hill",
    671: "Aztec Dirt: Chunky Temple",
    672: "Factory Dirt: Dark Room",
    673: "Isles Dirt: Cabin Isle",
    674: "Isles Dirt: Under Caves Lobby",
    675: "Isles Dirt: Aztec Roof",
    676: "Aztec Dirt: Oasis",
    677: "Forest Dirt: Mills Grass",
    678: "Forest Dirt: Beanstalk",
    679: "Galleon Dirt: Lighthouse",
    680: "Caves Dirt: Giant Kosha",
    681: "Castle Dirt: Top Floor",
    682: "Isles Dirt: Back of Prison",
    683: "Isles Dirt: Training Grounds Rear Tunnel",
    684: "Isles Dirt: Banana Hoard",
    685: "Isles Dirt: Castle Lobby",
    0x3CC: "Jungle Japes Enemy: Start",
    0x3CD: "Jungle Japes Enemy: Diddy Cavern",
    0x3CE: "Jungle Japes Enemy: Tunnel (0)",
    0x3CF: "Jungle Japes Enemy: Tunnel (1)",
    0x3D0: "Jungle Japes Enemy: Storm (0)",
    0x3D1: "Jungle Japes Enemy: Storm (1)",
    0x3D2: "Jungle Japes Enemy: Storm (2)",
    0x3D3: "Jungle Japes Enemy: Hive (0)",
    0x3D4: "Jungle Japes Enemy: Hive (1)",
    0x3D5: "Jungle Japes Enemy: Hive (2)",
    0x3D6: "Jungle Japes Enemy: Hive (3)",
    0x3D7: "Jungle Japes Enemy: Hive (4)",
    0x3D8: "Jungle Japes Enemy: Killed In Demo",
    0x3D9: "Jungle Japes Enemy: Near Underground",
    0x3DA: "Jungle Japes Enemy: Near Painting (0)",
    0x3DB: "Jungle Japes Enemy: Near Painting (1)",
    0x3DC: "Jungle Japes Enemy: Near Painting (2)",
    0x3DD: "Jungle Japes Enemy: Mountain",
    0x3DE: "Jungle Japes Enemy: Feather Tunnel",
    0x3DF: "Jungle Japes Enemy: Middle Tunnel",
    0x3E0: "Jungle Japes Lobby Enemy: Enemy (0)",
    0x3E1: "Jungle Japes Lobby Enemy: Enemy (1)",
    0x3E7: "Japes Mountain Enemy: Start (0)",
    0x3E8: "Japes Mountain Enemy: Start (1)",
    0x3E9: "Japes Mountain Enemy: Start (2)",
    0x3EA: "Japes Mountain Enemy: Start (3)",
    0x3EB: "Japes Mountain Enemy: Start (4)",
    0x3EC: "Japes Mountain Enemy: Near Gate Switch (0)",
    0x3ED: "Japes Mountain Enemy: Near Gate Switch (1)",
    0x3EE: "Japes Mountain Enemy: Hi Lo",
    0x3EF: "Japes Mountain Enemy: Conveyor (0)",
    0x3F0: "Japes Mountain Enemy: Conveyor (1)",
    0x3F1: "Japes Tiny Hive Enemy: First Room",
    0x3F2: "Japes Tiny Hive Enemy: Second Room (0)",
    0x3F3: "Japes Tiny Hive Enemy: Second Room (1)",
    0x3F4: "Japes Tiny Hive Enemy: Third Room (0)",
    0x3F5: "Japes Tiny Hive Enemy: Third Room (1)",
    0x3F6: "Japes Tiny Hive Enemy: Third Room (2)",
    0x3F7: "Japes Tiny Hive Enemy: Third Room (3)",
    0x3F8: "Japes Tiny Hive Enemy: Main Room",   
    0x3F9: "Angry Aztec Enemy: Vase Room (0)",
    0x3FA: "Angry Aztec Enemy: Vase Room (1)",
    0x3FB: "Angry Aztec Enemy: Tunnel Pad (0)",
    0x3FC: "Angry Aztec Enemy: Tunnel Cage (0)",
    0x3FD: "Angry Aztec Enemy: Tunnel Cage (1)",
    0x3FE: "Angry Aztec Enemy: Tunnel Cage (2)",
    0x3FF: "Angry Aztec Enemy: Starting Tunnel (0)",
    0x400: "Angry Aztec Enemy: Starting Tunnel (1)",
    0x401: "Angry Aztec Enemy: Oasis Door",
    0x402: "Angry Aztec Enemy: Tunnel Cage (3)",
    0x403: "Angry Aztec Enemy: Outside Llama",
    0x404: "Angry Aztec Enemy: Outside Tower",
    0x405: "Angry Aztec Enemy: Tunnel Pad (1)",
    0x406: "Angry Aztec Enemy: Near Candy",
    0x407: "Angry Aztec Enemy: Around Totem",
    0x408: "Angry Aztec Enemy: Starting Tunnel (2)",
    0x409: "Angry Aztec Enemy: Starting Tunnel (3)",
    0x40A: "Angry Aztec Enemy: Outside Snide",
    0x40B: "Angry Aztec Enemy: Outside 5DT",
    0x40C: "Angry Aztec Enemy: Near Sealed Quicksand Tunnel",
    0x40F: "Aztec Donkey 5DTemple Enemy: Start Trap (0)",
    0x410: "Aztec Donkey 5DTemple Enemy: Start Trap (1)",
    0x411: "Aztec Donkey 5DTemple Enemy: Start Trap (2)",
    0x412: "Aztec Donkey 5DTemple Enemy: End Trap (0)",
    0x413: "Aztec Donkey 5DTemple Enemy: End Trap (1)",
    0x414: "Aztec Donkey 5DTemple Enemy: End Trap (2)",
    0x415: "Aztec Donkey 5DTemple Enemy: End Path (0)",
    0x416: "Aztec Donkey 5DTemple Enemy: End Path (1)",
    0x417: "Aztec Donkey 5DTemple Enemy: Start Path",
    0x418: "Aztec Diddy 5DTemple Enemy: End Trap (0)",
    0x419: "Aztec Diddy 5DTemple Enemy: End Trap (1)",
    0x41A: "Aztec Diddy 5DTemple Enemy: End Trap (2)",
    0x41B: "Aztec Diddy 5DTemple Enemy: Start Left (0)",
    0x41C: "Aztec Diddy 5DTemple Enemy: Start Left (1)",
    0x41D: "Aztec Diddy 5DTemple Enemy: Reward",
    0x41E: "Aztec Diddy 5DTemple Enemy: Second Switch",
    0x41F: "Aztec Lanky 5DTemple Enemy: Joining Paths",
    0x420: "Aztec Lanky 5DTemple Enemy: End Trap",
    0x421: "Aztec Lanky 5DTemple Enemy: Reward",
    0x422: "Aztec Tiny 5DTemple Enemy: Start Right Front",
    0x423: "Aztec Tiny 5DTemple Enemy: Start Left Back",
    0x424: "Aztec Tiny 5DTemple Enemy: Start Right Back",
    0x425: "Aztec Tiny 5DTemple Enemy: Start Left Front",
    0x426: "Aztec Tiny 5DTemple Enemy: Reward (0)",
    0x427: "Aztec Tiny 5DTemple Enemy: Reward (1)",
    0x428: "Aztec Tiny 5DTemple Enemy: Dead End (0)",
    0x429: "Aztec Tiny 5DTemple Enemy: Dead End (1)",
    0x42A: "Aztec Chunky 5DTemple Enemy: Start Right",
    0x42B: "Aztec Chunky 5DTemple Enemy: Start Left",
    0x42C: "Aztec Chunky 5DTemple Enemy: Second Right",
    0x42D: "Aztec Chunky 5DTemple Enemy: Second Left",
    0x42E: "Aztec Chunky 5DTemple Enemy: Reward",
    0x42F: "Aztec Llama Temple Enemy: Kong Free Instrument",
    0x430: "Aztec Llama Temple Enemy: Dino Instrument",
    0x433: "Aztec Llama Temple Enemy: Right",
    0x434: "Aztec Llama Temple Enemy: Left",
    0x435: "Aztec Llama Temple Enemy: Melon Crate",
    0x436: "Aztec Llama Temple Enemy: Slam Switch",
    0x44B: "Aztec Tiny Temple Enemy: Guard Rotating (0)",
    0x44C: "Aztec Tiny Temple Enemy: Guard Rotating (1)",
    0x44D: "Aztec Tiny Temple Enemy: Main Room (0)",
    0x44E: "Aztec Tiny Temple Enemy: Main Room (1)",
    0x44F: "Aztec Tiny Temple Enemy: Main Room (2)",
    0x450: "Aztec Tiny Temple Enemy: Kong Room (0)",
    0x451: "Aztec Tiny Temple Enemy: Kong Room (1)",
    0x452: "Aztec Tiny Temple Enemy: Kong Room (2)",
    0x453: "Aztec Tiny Temple Enemy: Kong Room (3)",
    0x454: "Aztec Tiny Temple Enemy: Kong Room (4)",
    0x456: "Frantic Factory Enemy: Candy Cranky (0)",
    0x457: "Frantic Factory Enemy: Candy Cranky (1)",
    0x458: "Frantic Factory Enemy: Lobby Left",
    0x459: "Frantic Factory Enemy: Lobby Right",
    0x45A: "Frantic Factory Enemy: Storage Room",
    0x45B: "Frantic Factory Enemy: Block Tower (0)",
    0x45C: "Frantic Factory Enemy: Block Tower (1)",
    0x45D: "Frantic Factory Enemy: Block Tower (2)",
    0x45E: "Frantic Factory Enemy: Tunnel To Hatch",
    0x45F: "Frantic Factory Enemy: Tunnel To Prod (0)",
    0x460: "Frantic Factory Enemy: Tunnel To Prod (1)",
    0x461: "Frantic Factory Enemy: Tunnel To Block Tower",
    0x462: "Frantic Factory Enemy: Tunnel To Race (0)",
    0x463: "Frantic Factory Enemy: Tunnel To Race (1)",
    0x464: "Frantic Factory Enemy: Low Warp 4",
    0x465: "Frantic Factory Enemy: Diddy Switch",
    0x466: "Frantic Factory Enemy: To Block Tower Tunnel",
    0x467: "Frantic Factory Enemy: Dark Room (0)",
    0x468: "Frantic Factory Enemy: Dark Room (1)", 
    0x47B: "Frantic Factory Lobby Enemy: Enemy (0)",
    0x47C: "Gloomy Galleon Enemy: Chest Room (0)",
    0x47D: "Gloomy Galleon Enemy: Chest Room (1)",
    0x47E: "Gloomy Galleon Enemy: Near Vine Cannon",
    0x47F: "Gloomy Galleon Enemy: Cranky Cannon",
    0x483: "Gloomy Galleon Enemy: Peanut Tunnel",
    0x484: "Gloomy Galleon Enemy: Coconut Tunnel",
    0x485: "Galleon Lighthouse Enemy: Enemy (0)",
    0x486: "Galleon Lighthouse Enemy: Enemy (1)",
    0x495: "Fungi Forest Enemy: Hollow Tree (0)",
    0x496: "Fungi Forest Enemy: Hollow Tree (1)",
    0x497: "Fungi Forest Enemy: Hollow Tree Entrance",
    0x498: "Fungi Forest Enemy: Tree Melon Crate (0)",
    0x499: "Fungi Forest Enemy: Tree Melon Crate (1)",
    0x49A: "Fungi Forest Enemy: Tree Melon Crate (2)",
    0x49F: "Fungi Forest Enemy: Near Beanstalk (0)",
    0x4A0: "Fungi Forest Enemy: Near Beanstalk (1)",
    0x4A1: "Fungi Forest Enemy: Green Tunnel",
    0x4A2: "Fungi Forest Enemy: Near Low Warp 5",
    0x4A3: "Fungi Forest Enemy: Near Pink Tunnel Bounce Tag",
    0x4A4: "Fungi Forest Enemy: Near Giant Mushroom Rocketbarrel",
    0x4A5: "Fungi Forest Enemy: Between Yellow Tunnel And RB",
    0x4A6: "Fungi Forest Enemy: Near Cranky",
    0x4A7: "Fungi Forest Enemy: Near Pink Tunnel Giant Mushroom",
    0x4A8: "Fungi Forest Enemy: Giant Mushroom Rear Tag",
    0x4A9: "Fungi Forest Enemy: Near Face Puzzle",
    0x4AA: "Fungi Forest Enemy: Near Crown",
    0x4AB: "Fungi Forest Enemy: Near High Warp 5",
    0x4AC: "Fungi Forest Enemy: Top Of Mushroom",
    0x4AD: "Fungi Forest Enemy: Near Apple Dropoff",
    0x4AE: "Fungi Forest Enemy: Near DKPortal",
    0x4AF: "Fungi Forest Enemy: Near Well Tag",
    0x4B0: "Fungi Forest Enemy: Yellow Tunnel (0)",
    0x4B1: "Fungi Forest Enemy: Yellow Tunnel (1)",
    0x4B2: "Fungi Forest Enemy: Yellow Tunnel (2)",
    0x4B3: "Fungi Forest Enemy: Yellow Tunnel (3)",
    0x4B4: "Fungi Forest Enemy: Near Snide",
    0x4B5: "Fungi Forest Enemy: Near the hidden Rainbow Coin",
    0x4B6: "Fungi Forest Enemy: Near BBlast",
    0x4B7: "Fungi Forest Enemy: Near Dark Attic",
    0x4B8: "Fungi Forest Enemy: Near Well Exit",
    0x4B9: "Fungi Forest Enemy: Near Blue Tunnel",
    0x4BA: "Fungi Forest Enemy: Thornvine (0)",
    0x4BB: "Fungi Forest Enemy: Thornvine (1)",
    0x4BC: "Fungi Forest Enemy: Thornvine (2)",
    0x4BD: "Fungi Forest Enemy: Thornvine Entrance",
    0x4BE: "Forest Anthill Enemy: Gauntlet (0)",
    0x4BF: "Forest Anthill Enemy: Gauntlet (1)",
    0x4C0: "Forest Anthill Enemy: Gauntlet (2)",
    0x4C1: "Forest Anthill Enemy: Gauntlet (3)",
    0x4C2: "Forest Winch Room Enemy: Enemy",
    0x4C3: "Forest Thornvine Barn Enemy: Enemy",
    0x4C4: "Forest Mill Front Enemy: Enemy",
    0x4C5: "Forest Mill Back Enemy: Enemy",
    0x4C6: "Forest Giant Mushroom Enemy: Above Night Door",
    0x4C7: "Forest Giant Mushroom Enemy: Path (0)",
    0x4C8: "Forest Giant Mushroom Enemy: Path (1)", 
    0x4CC: "Forest Lanky Zingers Room Enemy: Enemy (0)",
    0x4CD: "Forest Lanky Zingers Room Enemy: Enemy (1)",
    0x4CE: "Forest Chunky Face Room Enemy: Enemy",
    0x4D2: "Crystal Caves Enemy: Start",
    0x4D3: "Crystal Caves Enemy: Near Ice Castle",
    0x4D4: "Crystal Caves Enemy: Outside 5DC",
    0x4D5: "Crystal Caves Enemy: 1DC Waterfall",
    0x4D6: "Crystal Caves Enemy: Near Funky",
    0x4D7: "Crystal Caves Enemy: Near Snide",
    0x4D8: "Crystal Caves Enemy: Near Bonus Room",
    0x4D9: "Crystal Caves Enemy: 1DC Headphones",
    0x4DB: "Caves Donkey Igloo Enemy: Right",
    0x4DC: "Caves Donkey Igloo Enemy: Left",
    0x4E2: "Caves Tiny Igloo Enemy: Big Enemy",
    0x4E8: "Caves Lanky Cabin Enemy: Near",
    0x4FF: "Creepy Castle Enemy: Near Bridge (0)",
    0x500: "Creepy Castle Enemy: Near Bridge (1)",
    0x501: "Creepy Castle Enemy: Wooden Extrusion (0)",
    0x502: "Creepy Castle Enemy: Wooden Extrusion (1)",
    0x503: "Creepy Castle Enemy: Near Shed",
    0x504: "Creepy Castle Enemy: Near Library",
    0x505: "Creepy Castle Enemy: Near Tower",
    0x506: "Creepy Castle Enemy: Museum Steps",
    0x507: "Creepy Castle Enemy: Near Low Cave",
    0x508: "Creepy Castle Enemy: Path To Low Kasplat",
    0x509: "Creepy Castle Enemy: Low TnS",
    0x50A: "Creepy Castle Enemy: Path To Dungeon",
    0x50B: "Creepy Castle Enemy: Near Headphones",
    0x50C: "Creepy Castle Lobby Enemy: Left",
    0x50D: "Creepy Castle Lobby Enemy: Far Right",
    0x50E: "Creepy Castle Lobby Enemy: Near Right",
    0x514: "Castle Ballroom Enemy: Start",
    0x515: "Castle Dungeon Enemy: Face Room",
    0x516: "Castle Dungeon Enemy: Chair Room",
    0x517: "Castle Dungeon Enemy: Outside Lanky Room",    
    0x51D: "Castle Lower Cave Enemy: Near Crypt",
    0x51E: "Castle Lower Cave Enemy: Stair Right",
    0x51F: "Castle Lower Cave Enemy: Stair Left",
    0x520: "Castle Lower Cave Enemy: Near Mausoleum",
    0x521: "Castle Lower Cave Enemy: Near Funky",
    0x522: "Castle Lower Cave Enemy: Near Tag",
    0x523: "Castle Crypt Enemy: Diddy Coffin (0)",
    0x524: "Castle Crypt Enemy: Diddy Coffin (1)",
    0x525: "Castle Crypt Enemy: Diddy Coffin (2)",
    0x526: "Castle Crypt Enemy: Diddy Coffin (3)",
    0x527: "Castle Crypt Enemy: Chunky Coffin (0)",
    0x528: "Castle Crypt Enemy: Chunky Coffin (1)",
    0x529: "Castle Crypt Enemy: Chunky Coffin (2)",
    0x52A: "Castle Crypt Enemy: Chunky Coffin (3)",
    0x52B: "Castle Crypt Enemy: Minecart Entry",
    0x52C: "Castle Crypt Enemy: Fork",
    0x52D: "Castle Crypt Enemy: Near Diddy",
    0x52E: "Castle Crypt Enemy: Near Chunky",
    0x52F: "Castle Mausoleum Enemy: Tiny Path",
    0x530: "Castle Mausoleum Enemy: Lanky Path (0)",
    0x531: "Castle Mausoleum Enemy: Lanky Path (1)",
    0x532: "Castle Upper Cave Enemy: Near Dungeon",
    0x534: "Castle Upper Cave Enemy: Near Pit",
    0x535: "Castle Upper Cave Enemy: Near Entrance",
    0x545: "Castle Library Enemy: Fork Left (0)",
    0x546: "Castle Library Enemy: Fork Left (1)",
    0x547: "Castle Library Enemy: Fork Center",
    0x548: "Castle Library Enemy: Fork Right",
    0x549: "Castle Museum Enemy: Main Floor (0)",
    0x54A: "Castle Museum Enemy: Main Floor (1)",
    0x54B: "Castle Museum Enemy: Main Floor (2)",
    0x54C: "Castle Museum Enemy: Main Floor (3)",
    0x54D: "Castle Museum Enemy: Start",
    0x558: "Castle Tree Enemy: Start Room (0)",
    0x559: "Castle Tree Enemy: Start Room (1)",
    0x55A: "Hideout Helm Enemy: Start (0)",
    0x55B: "Hideout Helm Enemy: Start (1)",
    0x55C: "Hideout Helm Enemy: Hill",
    0x55D: "Hideout Helm Enemy: Switch Room (0)",
    0x55E: "Hideout Helm Enemy: Switch Room (1)",
    0x55F: "Hideout Helm Enemy: Mini Room (0)",
    0x560: "Hideout Helm Enemy: Mini Room (1)",
    0x561: "Hideout Helm Enemy: Mini Room (2)",
    0x562: "Hideout Helm Enemy: Mini Room (3)",
    0x563: "Hideout Helm Enemy: DKRoom",
    0x564: "Hideout Helm Enemy: Chunky Room (0)",
    0x565: "Hideout Helm Enemy: Chunky Room (1)",
    0x566: "Hideout Helm Enemy: Tiny Room",
    0x567: "Hideout Helm Enemy: Lanky Room (0)",
    0x568: "Hideout Helm Enemy: Lanky Room (1)",
    0x569: "Hideout Helm Enemy: Diddy Room (0)",
    0x56A: "Hideout Helm Enemy: Diddy Room (1)",
    0x56B: "Hideout Helm Enemy: Nav Right",
    0x56C: "Hideout Helm Enemy: Nav Left",
    0x56D: "Isles Enemy: Pineapple Cage (0)",
    0x56E: "Isles Enemy: Fungi Cannon (0)",
    0x56F: "Isles Enemy: Japes Entrance",
    0x570: "Isles Enemy: Monkeyport Pad",
    0x571: "Isles Enemy: Upper Factory Path",
    0x572: "Isles Enemy: Near Aztec",
    0x573: "Isles Enemy: Fungi Cannon (1)",
    0x574: "Isles Enemy: Pineapple Cage (1)",
    0x575: "Isles Enemy: Lower Factory Path (0)",
    0x576: "Isles Enemy: Lower Factory Path (1)",
}

location_name_to_flag = {v: k for k, v in location_flag_to_name.items()}
